### ISSUE TITLE
Error - ChainId mismatch on Trust Chrome Wallet

### ISSUE THREAD

**Issue by kkatusic** [Web3Auth/sign-in-with-solana#34]
**Steps to reproduce**

Please tell us exactly how to reproduce the problem you are running into.

1. Go to Google Chrome Browser
2. Connect your Trust Wallet
3. Go to some project link: [https://staging.giveth.io/donate/a-delicious-help](https://staging.giveth.io/donate/a-delicious-help)
4. You will see "Sign In" button
5. Click on button

**Screenshots or Video**

![Screenshot 2024-08-21 at 13 56 19](https://github.com/user-attachments/assets/0a47c9ad-ad18-4a78-87c8-34b9fc66364c)

**Logs**

```console
WalletSignMessageError: Error Calling Method: signMessage
    at StandardWalletAdapter._StandardWalletAdapter_signMessage [as signMessage] (adapter.js:374:1)
    at async eval (WalletProviderBase.js:175:1)
    at async signBySolana (generalWalletProvider.tsx:144:21)
    at async onClick (SignWithWalletModal.tsx:318:10) StandardWalletAdapter {_events: Events, _eventsCount: 4, signIn: ƒ, signTransaction: ƒ, signAllTransactions: ƒ, …}
```

**Desktop (please complete the following information):**
 -OS: MAC M1 OS Sonoma 14.6.1
 -Browser Chrome
 -Version 127.0.6533.120
 -Trust Wallet extension for Chrome: 2.19.0

**Comment by ferrarikol64-spec** [comment]
WalletSignMessageError: Error Calling Method: signMessage
    at StandardWalletAdapter._StandardWalletAdapter_signMessage [as signMessage] (adapter.js:374:1)
    at async eval (WalletProviderBase.js:175:1)
    at async signBySolana (generalWalletProvider.tsx:144:21)
    at async onClick (SignWithWalletModal.tsx:318:10) StandardWalletAdapter {_events: Events, _eventsCount: 4, signIn: ƒ, signTransaction: ƒ, signAllTransactions: ƒ, …}
